### ISSUE TITLE
Hyperparameters

### ISSUE THREAD

**Issue by ghost** [google/meta_tagger#1]
Hi, I'm having trouble achieving the 97.96 PTB score with your tool.
Can you provide the config.json file used in the paper to show that this tagger can indeed achieve this result?
Thanks!

**Comment by bohnetbd** [comment]
Hi !
sorry for the late reply. I have overlooked your message. I have set early stopping to the right value. Now you should land in the range. Please, let me know if this worked.

Best,
Bernd
